import { Category, Expense } from "@/types";

export const DEFAULT_CATEGORIES: Category[] = [
  {
    id: "cat_1",
    name: "Food & Dining",
    color: "#10B981", // Emerald
    icon: "utensils",
    userId: "demo_user",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    _count: { expenses: 4 },
  },
  {
    id: "cat_2",
    name: "Housing & Rent",
    color: "#8B5CF6", // Purple
    icon: "home",
    userId: "demo_user",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    _count: { expenses: 2 },
  },
  {
    id: "cat_3",
    name: "Shopping & Tech",
    color: "#3B82F6", // Blue
    icon: "shopping-bag",
    userId: "demo_user",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    _count: { expenses: 3 },
  },
  {
    id: "cat_4",
    name: "Subscriptions",
    color: "#A855F7", // Purple Accent
    icon: "tv",
    userId: "demo_user",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    _count: { expenses: 3 },
  },
  {
    id: "cat_5",
    name: "Transportation",
    color: "#F59E0B", // Amber
    icon: "car",
    userId: "demo_user",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    _count: { expenses: 2 },
  },
  {
    id: "cat_6",
    name: "Utilities & Bills",
    color: "#06B6D4", // Cyan
    icon: "zap",
    userId: "demo_user",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    _count: { expenses: 1 },
  },
];

const now = new Date();
const formatIso = (daysAgo: number) => {
  const d = new Date(now);
  d.setDate(d.getDate() - daysAgo);
  return d.toISOString();
};

export const DEFAULT_EXPENSES: Expense[] = [
  {
    id: "exp_1",
    title: "Linear & GitHub Pro Subscriptions",
    amount: 1499.0,
    date: formatIso(0),
    notes: "Monthly subscriptions for development & issue tracking",
    paymentMethod: "UPI",
    categoryId: "cat_4",
    category: DEFAULT_CATEGORIES[3],
    userId: "demo_user",
    createdAt: formatIso(0),
    updatedAt: formatIso(0),
  },
  {
    id: "exp_2",
    title: "Grocery Shopping at Nature's Basket",
    amount: 3450.0,
    date: formatIso(0),
    notes: "Weekly groceries, fruits & organic produce",
    paymentMethod: "UPI",
    categoryId: "cat_1",
    category: DEFAULT_CATEGORIES[0],
    userId: "demo_user",
    createdAt: formatIso(0),
    updatedAt: formatIso(0),
  },
  {
    id: "exp_3",
    title: "MacBook Pro Sleeve & USB-C Hub",
    amount: 4290.0,
    date: formatIso(1),
    notes: "Leather sleeve and Satechi multi-port hub",
    paymentMethod: "CREDIT_CARD",
    categoryId: "cat_3",
    category: DEFAULT_CATEGORIES[2],
    userId: "demo_user",
    createdAt: formatIso(1),
    updatedAt: formatIso(1),
  },
  {
    id: "exp_4",
    title: "Blue Tokai Coffee & Bakery",
    amount: 680.0,
    date: formatIso(2),
    notes: "Cold brew roast & artisanal croissants",
    paymentMethod: "UPI",
    categoryId: "cat_1",
    category: DEFAULT_CATEGORIES[0],
    userId: "demo_user",
    createdAt: formatIso(2),
    updatedAt: formatIso(2),
  },
  {
    id: "exp_5",
    title: "Apartment Monthly Maintenance & HOA",
    amount: 18500.0,
    date: formatIso(3),
    notes: "Building maintenance, security & parking fees",
    paymentMethod: "BANK_TRANSFER",
    categoryId: "cat_2",
    category: DEFAULT_CATEGORIES[1],
    userId: "demo_user",
    createdAt: formatIso(3),
    updatedAt: formatIso(3),
  },
  {
    id: "exp_6",
    title: "Uber Cab to Business Park",
    amount: 420.0,
    date: formatIso(4),
    notes: "Morning commute during heavy rain",
    paymentMethod: "UPI",
    categoryId: "cat_5",
    category: DEFAULT_CATEGORIES[4],
    userId: "demo_user",
    createdAt: formatIso(4),
    updatedAt: formatIso(4),
  },
  {
    id: "exp_7",
    title: "AWS Cloud Infrastructure Hosting",
    amount: 5400.0,
    date: formatIso(5),
    notes: "EC2 instances, S3 storage & DNS hosting",
    paymentMethod: "CREDIT_CARD",
    categoryId: "cat_4",
    category: DEFAULT_CATEGORIES[3],
    userId: "demo_user",
    createdAt: formatIso(5),
    updatedAt: formatIso(5),
  },
  {
    id: "exp_8",
    title: "Team Dinner at Pa Pa Ya",
    amount: 7200.0,
    date: formatIso(7),
    notes: "Quarterly team milestone celebration dinner",
    paymentMethod: "CREDIT_CARD",
    categoryId: "cat_1",
    category: DEFAULT_CATEGORIES[0],
    userId: "demo_user",
    createdAt: formatIso(7),
    updatedAt: formatIso(7),
  },
  {
    id: "exp_9",
    title: "High-Speed Fiber Broadband Bill",
    amount: 1499.0,
    date: formatIso(10),
    notes: "Airtel Xstream 300Mbps symmetrical fiber connection",
    paymentMethod: "UPI",
    categoryId: "cat_6",
    category: DEFAULT_CATEGORIES[5],
    userId: "demo_user",
    createdAt: formatIso(10),
    updatedAt: formatIso(10),
  },
  {
    id: "exp_10",
    title: "Cult.fit Club Gym Membership",
    amount: 14500.0,
    date: formatIso(12),
    notes: "Annual Cult Pass Elite membership",
    paymentMethod: "CREDIT_CARD",
    categoryId: "cat_4",
    category: DEFAULT_CATEGORIES[3],
    userId: "demo_user",
    createdAt: formatIso(12),
    updatedAt: formatIso(12),
  },
];
